SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS, BOOK B, AUTHOR A
WHERE B.BOOK_ID = BS.BOOK_ID and A.AUTHOR_ID = B.AUTHOR_ID
and SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC
# 2022년 1월 도서판매 기준
# 저자별, 카테고리별 매출액, 저자ID, 저자명, 카테고리, 매출액
# 저자ID 기준으로 오름차순, 같다면 카테고리 기준으로 내림차순.