-- 코드를 작성해주세요
SELECT i.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO i
WHERE i.ITEM_ID NOT IN
(SELECT PARENT_ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IS NOT NULL
GROUP BY PARENT_ITEM_ID)
ORDER BY i.ITEM_ID DESC;


# 더이상 업그레이드 할수 없는 아이템의 ID, 아이템 명, 아이템 희귀도
# ID기준으로 내림차순 정렬
# ,