-- 코드를 작성해주세요
WITH P1 AS(SELECT PARENT_ID AS ID, COUNT(PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY PARENT_ID)

SELECT E.ID, IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN P1
ON E.ID = P1.ID
ORDER BY E.ID;


# ID, 자식의수 CHILD_COUNT 없으면 0
# ID에대해 오름차순
# parent의개수를 구하면 자식의 개수를 알수있음