-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT p INNER JOIN OFFLINE_SALE os
ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;

# PRICE * SALES_AMOUNT
# 상품코드 별 매출액 합계를 출력
# 매출액 기준으로 내림차순, 같다면 상품코드 기준으로 오름차순