-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = "2022" and MONTH(SALES_DATE) = '3'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = "2022" and MONTH(SALES_DATE) = '3'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID




#2022년 3월 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량
#OFFLINE_SALE -> USER_ID == null
# 판매일을 기준으로 오름차순 정렬, 상품ID 기준으로 오름차순, 유저ID 기준으로 오름차순