-- 코드를 입력하세요
SELECT fo.PRODUCT_ID, PRODUCT_NAME, (PRICE * SUM(AMOUNT)) TOTAL_SALES
FROM FOOD_ORDER fo JOIN FOOD_PRODUCT fp
ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
GROUP BY fo.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fo.PRODUCT_ID

# 생산일자 2022년 5월
# 식품ID, 시굼 이름, 총매출