-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b 
JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES

# 회원, 닉네임, 총 거래김액
# 완료된 중고 거래 총금액이 70만원 이상
# USER_ID를 JOIN 했을때
# STATUS = "DONE"
# 총거래금액 기준으로 오름차순 정렬