-- 코드를 작성해주세요
WITH P1 AS (
    SELECT *,
    (CASE WHEN AVG_SCORE >= 96 THEN 'S'
    WHEN AVG_SCORE >= 90 THEN 'A'
    WHEN AVG_SCORE >= 80 THEN 'B'
    ELSE 'C'
    END) AS GRADE
    FROM (SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO) P2
)




SELECT he.EMP_NO, EMP_NAME, GRADE,
(
    CASE WHEN GRADE = 'S' THEN SAL * 0.2
    WHEN GRADE = 'A' THEN SAL * 0.15
    WHEN GRADE = 'B' THEN SAL * 0.1
    ELSE 0
    END
) AS BONUS
FROM HR_EMPLOYEES he INNER JOIN P1
ON he.EMP_NO = P1.EMP_NO
ORDER BY he.EMP_NO
