-- 코드를 입력하세요
WITH p1 AS (SELECT MEMBER_ID, COUNT(*) REVIEW_COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY REVIEW_COUNT DESC)



SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE m JOIN REST_REVIEW r
ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM P1
    WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) MAX_REVIEW_COUNT
    FROM P1)
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;



# 리뷰를 가장많이 작성한 회원