SELECT N2.ITEM_ID, N2.ITEM_NAME, N2.RARITY
FROM
(SELECT i2.ITEM_ID
FROM ITEM_INFO i2
WHERE RARITY = 'RARE') AS N1,
(SELECT i.ITEM_ID, ITEM_NAME, RARITY, t.PARENT_ITEM_ID
FROM ITEM_INFO i, ITEM_TREE t
WHERE i.ITEM_ID = t.ITEM_ID) AS N2
WHERE N1.ITEM_ID = N2.PARENT_ITEM_ID
ORDER BY N2.ITEM_ID DESC