-- 코드를 작성해주세요
WITH P1 AS (
    SELECT ID
    FROM ECOLI_DATA
)

SELECT E1.ID, E1.GENOTYPE, E2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E1 INNER JOIN ECOLI_DATA E2
ON E1.PARENT_ID = E2.ID
WHERE (E2.GENOTYPE & E1.GENOTYPE) = E2.GENOTYPE
ORDER BY E1.ID

# NULL 자동 삭제
# 부모의 형질을 모두 보유한
# 부모의 GENOTYPE & 자식의 GENOTYPE = 1인것들