WITH P1 AS
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR2, MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY YEAR2
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
, ((SELECT MAXSIZE FROM P1 WHERE YEAR = YEAR2) - SIZE_OF_COLONY) AS YEAR_DEV
,ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;


# YEAR, YEAR_DEV, ID
# YEAR_DEV : 대장균 크기의 편차
# 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기
# 연도에 대해 오름차순
# 같은 연도면, 대장균 크기의 편차에따라 오름차순