-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO fi INNER JOIN
(SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE) fo INNER JOIN FISH_NAME_INFO fni
ON fi.FISH_TYPE = fo.FISH_TYPE AND fi.FISH_TYPE = fni.FISH_TYPE
WHERE MAX_LENGTH = LENGTH
ORDER BY ID
    

