-- 코드를 작성해주세요
WITH SCORE_BOARD AS(SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO)

SELECT SCORE, he.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES he INNER JOIN SCORE_BOARD sb
ON he.EMP_NO = sb.EMP_NO
WHERE SCORE = (SELECT MAX(SCORE)
                          FROM SCORE_BOARD);

