SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF f JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER

# 상반기동안 각 아이스크림 성분 타입, 성분타입에 대한 아이스크림 총 주문량
# 총 주문량(TOTAL_ORDER)이 작은 순서로 조회
